#!/usr/bin/env sh

podman run \
      -it \
      --rm \
      --init \
      --device /dev/fuse \
      -v $HOME/.config/opencode:/root/.config/opencode \
      -v $HOME/.local/share/opencode:/root/.local/share/opencode \
      -v $HOME/.local/state/opencode:/root/.local/state/opencode \
      -v $HOME/.cache/opencode:/root/.cache/opencode \
      -v $HOME/hulks/hulk:$HOME/hulks/hulk \
      -v $PWD:$PWD \
      -w $PWD \
      llmc:latest \
      bash
